version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
    depends_on:
      - wp_database
    environment:
      WORDPRESS_DB_HOST: wp_database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
    networks:
      - app_network

  wp_database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  wordpress-data:
  mysql-data:
